services:
  php-fpm:
    container_name: php-fpm
    build: 
      context: ./php-fpm
    volumes:
      - type: bind
        source: ./
        target: /var/www
      - sock:/sock
  
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    depends_on:
      - php-fpm
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./
        target: /var/www
      - sock:/sock
      
volumes:
  sock: