version: '3'
services:

  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_HOST: '${MYSQL_HOST}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ${APP_DIR}:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - ${APP_DIR}:/var/www
     - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_ALLOW_ROOT_PASSWORD: ${MYSQL_ALLOW_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./.mysql:/var/lib/mysql
    networks:
      - app-network
    
  npm_build_tools:
    build:
      context: .
      dockerfile: ./npm_build_tools/Dockerfile
    container_name: npm_build_tools
    tty: true
    user:
      "1000:1000"
    working_dir: /var/www
    volumes:
      - ${APP_DIR}:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
